In [13]:
import numpy as np

W = np.ones(shape=(3, 4)) * float(1)/3
print W
W.shape[0] # row
W.shape[1] # col


c = np.array([[ 1, 2, 3],
              [-1, 1, 4]])
A = np.square(c)
print A
print np.sum(A, axis = 1) # sum each row

[[ 0.33333333  0.33333333  0.33333333  0.33333333]
 [ 0.33333333  0.33333333  0.33333333  0.33333333]
 [ 0.33333333  0.33333333  0.33333333  0.33333333]]
[[ 1  4  9]
 [ 1  1 16]]
[14 18]


In [11]:
from scipy.sparse import csr_matrix
import numpy as np

row = np.array([0, 0, 1, 2, 2, 2, 3])
col = np.array([0, 2, 2, 0, 1, 2, 1])
data1 = np.array([1, 2, 3, 4, 5, 6, 2])
data2 = np.array([2, 3, 4, 5, 6, 2, 1])
M1 = csr_matrix((data1, (row, col)), shape=(4, 3))
M2 = csr_matrix((data2, (row, col)), shape=(4, 3))
print M1.toarray()
print M2.toarray()

np.multiply(M1.toarray(), M2.toarray())
np.dot(M1.toarray(), M2.toarray().T)
# print M[1:3].toarray()  # slices out [1, 3)

# print M.toarray()
# denom = np.array([2, 2, 2])
# print np.divide(M.toarray().T, denom.T)
# M.getrow(0).toarray() # get the 0-th row
# M.get_shape()[0] # row len
# M.get_shape()[1] # col len

[[1 0 2]
 [0 0 3]
 [4 5 6]
 [0 2 0]]
[[2 0 3]
 [0 0 4]
 [5 6 2]
 [0 1 0]]


array([[ 8,  8,  9,  0],
       [ 9, 12,  6,  0],
       [26, 24, 62,  5],
       [ 0,  0, 12,  2]])

In [25]:
l = [1] * 5
out = np.exp(l)
print out

[ 2.71828183  2.71828183  2.71828183  2.71828183  2.71828183]


In [29]:
import math
print math.exp(0.3)/6.74929

0.200000119653


In [33]:
iter = 0
batch_size = 3
while batch_size * (iter + 1) < 50: 
    for i in range(batch_size * iter, batch_size * (iter+1)):
        print i
    iter += 1

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47


In [47]:
l1 = [1, 3, 4, 6, 3]
l2 = [4, 2, 4, 3, 3]
l1 + l2

[1, 3, 4, 6, 3, 4, 2, 4, 3, 3]

In [43]:
import math
math.log(2.71828)

0.999999327347282

In [45]:
10E-7


1e-06

In [46]:
l = 'lksdf   lkdsfjsl ldkfjsksd lksjfkjsdf    kdjf  '
print (l.split())

['lksdf', 'lkdsfjsl', 'ldkfjsksd', 'lksjfkjsdf', 'kdjf']
